name: Desafio-workflow

on:
    push:
        branches: [ cicd-learning ]

    pull_request:
        branches: [ master ]

    workflow_dispatch:

jobs:
    build:
        runs-on:
            - desafio-label

        steps:
            - uses: actions/checkout@v4

            - name: Install Dependences Composer
              run: |
                docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 composer install
                docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 composer dumpautoload -o

            - name: Copy .env.example
                run: docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 cp .env.example .env

            - name: Running Migrations
                run: docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 php artisan migrate
            
            - name: Clear Caches
              run: | 
                docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 php artisan optimize:clear
                docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 php artisan optimize
            
            - name: Teste (.env.testing)
              run: docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 php artisan test --env="testing"

            - name: Clear Caches
              run: |
                docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 php artisan optimize:clear
                docker exec -t -w /projects/actions-runner/_work/desafio-backend-01/desafio-backend-01 docker-php-fpm-1 php artisan optimize